const Discord = require('discord.js');
const bot = new Discord.Client();
const prefix = "."

bot.on('ready', ()=>{
    bot.user.setActivity(`${bot.guilds.cache.size} servers.`, {type: 'WATCHING'})
    console.log('BOT Online.')
})

bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}training`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "trainings") return message.author.send('Please use this command in the training channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("A Training is being hosted!")
        .setDescription(arg)
        .setColor("0x8b0000")
        .setFooter(`Shouted by ${message.author.username}.`)
        message.channel.send('@everyone', embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}hentaishout`)) {
    if(message.author.bot) return;
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
        message.channel.send("MM, TASTY HENTAI https://cdn.discordapp.com/attachments/793540101565186108/794294410280042506/OIP_34.jpeg")
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}raid`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "raids") return message.author.send('Please use this command in the raids channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("A Raid is being hosted!")
        .setDescription(arg)
        .setColor("0x8b0000")
        .setFooter(`Shouted by ${message.author.username}.`)
        message.channel.send('@everyone', embed)
    }
});
bot.on("message", (message) => {
    if(message.content.startsWith(`${prefix}help`)) {
    if(message.author.bot) return;
    const embed = new Discord.MessageEmbed()
        .setTitle('Showing command list.')
        .addField('.training', '*Description:* Generates an embed used for trainings, include links or any additional notes in the command..')
        .addField('.raid', '*Description:* Generates an embed like the training one, except it\'s used for raids, include links and any additional notes in the command.')
        .addField('.recruitment', '*Description:* Generates an embed used for recruitment sessions, make sure to include your profile link and any information regarding the booth.')
        .addField('.hentaishout', '*Description:* BRO, SO TASTY MMM, I LOVE NEKOS -invernus')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    if(message.author.bot) return;
    const embed = new Discord.MessageEmbed()
        .addField('BOT invite link:', 'https://discord.com/api/oauth2/authorize?client_id=750968965613879349&permissions=257024&scope=bot')
        .addField('Official discord server link:', 'https://discord.gg/q8ZjH4V')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
    if(message.content.includes(`${prefix}invite`)) {
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(!arg) return;
    if(message.author.bot) return;
    if (!message.member.hasPermission(["EMBED_LINKS"])) return;
    let embed = new Discord.MessageEmbed()
        .setDescription('Found a bug? And don\'t know where to report it? Join our official server to report bugs! You can find the invite link in the command **.invite**!')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
    if(message.content.includes(`${prefix}report`)) {
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    if(message.author.bot) return;
    const embed = new Discord.MessageEmbed()
        .setTitle('Frequently asked questions')
        .addField('Can I put markdowns in my embed?', 'Yes, you can.')
        .addField('Can I put how many words I want?', 'Sadly, max words for an embed is 1024. This means, there is a limit per embed. If your embed doesn\'t show up, it\'s more likely that you have reached the max texts.')
        .addField('My embed doesn\'t show up! What do I do?', 'If an embed doesn\'t show up, you probably do not have enough permission to use it, or, you have reached the max words. Otherwise, please run the command **.status**, if no response from the bot, we recommend waiting a few minutes, as there may be a downtime.')
        .addField('If you\'d like to suggest questions, join our discord server!', 'You can find the link in **.invite**.')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
    if(message.content.includes(`${prefix}faq`)) {
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    if(message.author.bot) return;
    const embed = new Discord.MessageEmbed()
        .addField('Current status:', 'Up and running.')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
    if(message.content.includes(`${prefix}status`)) {
        message.channel.send(embed)
    }
});


bot.login(process.env.token)
