const Discord = require('discord.js');
const bot = new Discord.Client();
const prefix = "."

bot.on('ready', ()=>{
    bot.user.setActivity(`SCP Foundation`, {type: 'WATCHING'})
    console.log('BOT Online.')
})

bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}event`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "event-announcements") return message.author.send('Please use this command in the training channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("Event Shout")
        .setDescription(arg)
        .setColor("0x8b0000")
        .setFooter(`Shouted by ${message.author.username}.`)
        message.channel.send('@here', embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}event`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "event-announcements") return message.author.send('Please use this command in the training channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("Event Shout")
        .setDescription(arg)
        .setColor("0x8b0000")
        .setFooter(`Shouted by ${message.author.username}.`)
        message.channel.send('@here', embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}raid`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "raids") return message.author.send('Please use this command in the raids channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("A Raid is being hosted!")
        .setDescription(arg)
        .setColor("0x8b0000")
        .setFooter(`Shouted by ${message.author.username}.`)
        message.channel.send('@everyone', embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}recruitment`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "events") return message.author.send('Please use this command in the events channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("A recruitment session is being hosted!")
        .setDescription(`*Come help us recruit more members!*\n \n${arg}`)
        .setColor("0x8b0000")
        .setFooter(`Shouted by ${message.author.username}.`)
        message.channel.send('e', embed)
    }
});
bot.on("message", (message) => {
    if(message.content.startsWith(`${prefix}help`)) {
    if(message.author.bot) return;
    const embed = new Discord.MessageEmbed()
        .setTitle('Showing command list.')
        .addField('N/A', 'Public commands are currently not available.')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    if(message.author.bot) return;
    const embed = new Discord.MessageEmbed()
        .addField('Current status:', 'Up and running.')
        .setColor("RANDOM")
        .setFooter(`Generated by ${message.author.username}.`)
    if(message.content.includes(`${prefix}status`)) {
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}o5invites`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "permanent-discord-invites") return message.author.send('Please use this command in the O5 council channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("Discord Invites")
        .setDescription(arg)
        .setColor("0xffa500")
        .setFooter(`All invites listed above are strictly confidential and any leaking will lead to consequences`)
        message.channel.send(embed)
    }
});
bot.on("message", (message) => {
    var arg = message.content.split(" ").slice(1).join(" ");
    if(message.content.startsWith(`${prefix}o5docs`)) {
    if(!arg) return;
    if(message.author.bot) return;
    if(message.channel.name !== "o5-documents") return message.author.send('Please use this command in the O5 council channel.')
    if (!message.member.hasPermission(["MENTION_EVERYONE"])) return;
    let embed = new Discord.MessageEmbed()
        .setTitle("O5 Council Documents")
        .setDescription(arg)
        .setColor("0xffa500")
        .setFooter(`All documents listed above are strictly confidential and any leaking will lead to consequences`)
        message.channel.send(embed)
    }
});

bot.login(process.env.token)
